project_id = "dzvjybtofvbxtuagtzng"

[functions.rdw-lookup]
verify_jwt = false

[functions.postcode-lookup]
verify_jwt = false

[functions.extract-photo-data]
verify_jwt = false

[functions.process-reminders]
verify_jwt = false
